/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Periodontitis.gltf 
Author: SofiaFolguera (https://sketchfab.com/SofiaFolguera)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arcadainferiorprueba3-0cfb2214cffd4512a288dc72e4a08b32
Title: arcadainferiorprueba3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function House_Periodontitis(props) {
  const { nodes, materials } = useGLTF('/Periodontitis.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_15.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_17.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_21.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_23.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Material.001']} />
    </group>
  )
}


useGLTF.preload('/Periodontitis.gltf')
