/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cancer.gltf 
Author: University of Dundee, School of Dentistry (https://sketchfab.com/DundeeDental)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/lymphatics-of-head-and-neck-5abcaca1574248c0860ae1d81b06998d
Title: Lymphatics of head and neck
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function House_Cancer(props) {
  const { nodes, materials } = useGLTF('/Cancer.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1544.994, 1190.955]} rotation={[-3.006, 0, 0]}>
        <group position={[-185.313, -1641.351, -207.591]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.defaultMat} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.defaultMat_0} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.defaultMat_1} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.defaultMat_2} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.defaultMat_3} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.defaultMat_4} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.defaultMat_5} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.defaultMat_5} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.defaultMat_6} />
          <mesh geometry={nodes.Object_54.geometry} material={materials.defaultMat_6} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.defaultMat_6} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.defaultMat_6} />
        </group>
      </group>
    </group>
  )
}


useGLTF.preload('/Cancer.gltf')
