/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Caries.gltf 
Author: SofiaFolguera (https://sketchfab.com/SofiaFolguera)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paciente-a-arcada-inferior-609c6e791b3a4983bd5b2d0520dbe42e
Title: Paciente A arcada inferior
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function House_Caries(props){
  const { nodes, materials } = useGLTF('/Caries.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}



useGLTF.preload('/Caries.gltf')
