/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 house_modeloquiste.gltf 
Author: drpcnaidu (https://sketchfab.com/drpcnaidu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ortho-study-models-sr12-ef47849bd84d47628cb4f7cd699b524a
Title: Ortho Study Models sr12
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/house_modeloquiste.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[7.182, -2.802, 2.802]} rotation={[0, 0, -Math.PI]}>
        <group position={[0.314, -10.087, 3.93]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.material_3} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/house_modeloquiste.gltf')
