/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Halitosis.gltf 
Author: Se Won An (https://sketchfab.com/sewonan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/30-on-full-mandibular-dentoform-16ec8610299f4d509df687143c016837
Title: #30 on Full Mandibular Dentoform
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function House_Halitosis(props) {
  const { nodes, materials } = useGLTF('/Halitosis.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.09, -0.157, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/Halitosis.gltf')
