/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Traumatismo.gltf 
Author: J. Víctor Febles (https://sketchfab.com/JVICTORFEBLESGLEZ)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mandibula-neandertal-c93c0f237c7443c6aa3111b1b9ca4c05
Title: Mandíbula Neandertal
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Traumatismo.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.766, 0.795, 1.03]}>
        <group position={[-0.733, -0.534, -0.536]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Traumatismo.gltf')
