/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 house.gltf 
Author: anknv (https://sketchfab.com/anknv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dental-scan-for-a-denture-52736c16312d486097962b40f974f6df
Title: Dental Scan for a denture
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/house.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.126, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.61, -10.121, -1.202]} rotation={[-2.967, -1.571, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['MaterialName.014']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['MaterialName.014']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['MaterialName.014']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['MaterialName.014']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['MaterialName.014']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['MaterialName.014']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['MaterialName.014']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['MaterialName.014']} />
          </group>
          <group position={[1.764, 12.009, -2.102]} rotation={[-2.967, -1.571, 0]}>
            <mesh geometry={nodes.Object_17.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_18.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_19.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_20.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_21.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_22.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_23.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_24.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_25.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_26.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_27.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_28.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_29.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_30.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_31.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_32.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_33.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_34.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_35.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_36.geometry} material={materials['MaterialName.013']} />
            <mesh geometry={nodes.Object_37.geometry} material={materials['MaterialName.013']} />
          </group>
          <mesh geometry={nodes.Object_13.geometry} material={materials.material_0} position={[18.827, -9.737, -20.123]} rotation={[-2.967, -1.571, 0]} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.material_0} position={[15.28, -10.188, -8.229]} rotation={[-2.967, -1.571, 0]} />
          <mesh geometry={nodes.Object_39.geometry} material={materials['Material.001']} position={[0, -17.064, 0]} scale={[0.1, 1, 0.1]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/house.gltf')
