/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 house_diente.gltf 
Author: alecz1k (https://sketchfab.com/alecz1k)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/teeth-e9ca8b835d554860bd6757cd44905f1f
Title: Teeth
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/house_diente.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.024, 0.263, -2.202]} rotation={[1.014, -0.003, 0.022]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Layer_1__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_2__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_5__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_6__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_7__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_8__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_9__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_10__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_11__0.geometry} material={materials['Scene_-_Root']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/house_diente.gltf')
