/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 house_modelo1.gltf 
Author: thunk3d.scanner (https://sketchfab.com/thunk3d.scanner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/colorful-dental-model-e45f1cefbe9d4881b728c1d9f37c57e0
Title: Colorful dental model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/house_modelo1.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[185.98, -194.95, 354.49]} rotation={[-0.688, 0.264, 2.944]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Scene_-_Root']} />
      </group>
    </group>
  )
}

useGLTF.preload('/house_modelo1.gltf')
